// Code generated by ent, DO NOT EDIT.

package outboxevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the outboxevent type in the database.
	Label = "outbox_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAggregateType holds the string denoting the aggregate_type field in the database.
	FieldAggregateType = "aggregate_type"
	// FieldAggregateID holds the string denoting the aggregate_id field in the database.
	FieldAggregateID = "aggregate_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldEventVersion holds the string denoting the event_version field in the database.
	FieldEventVersion = "event_version"
	// FieldPayloadJSON holds the string denoting the payload_json field in the database.
	FieldPayloadJSON = "payload_json"
	// FieldMetadataJSON holds the string denoting the metadata_json field in the database.
	FieldMetadataJSON = "metadata_json"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// Table holds the table name of the outboxevent in the database.
	Table = "outbox_events"
)

// Columns holds all SQL columns for outboxevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAggregateType,
	FieldAggregateID,
	FieldEventType,
	FieldEventVersion,
	FieldPayloadJSON,
	FieldMetadataJSON,
	FieldStatus,
	FieldRetryCount,
	FieldNextAttemptAt,
	FieldPublishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	AggregateTypeValidator func(string) error
	// AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	AggregateIDValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultEventVersion holds the default value on creation for the "event_version" field.
	DefaultEventVersion string
	// PayloadJSONValidator is a validator for the "payload_json" field. It is called by the builders before save.
	PayloadJSONValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultNextAttemptAt holds the default value on creation for the "next_attempt_at" field.
	DefaultNextAttemptAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the OutboxEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAggregateType orders the results by the aggregate_type field.
func ByAggregateType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateType, opts...).ToFunc()
}

// ByAggregateID orders the results by the aggregate_id field.
func ByAggregateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByEventVersion orders the results by the event_version field.
func ByEventVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventVersion, opts...).ToFunc()
}

// ByPayloadJSON orders the results by the payload_json field.
func ByPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadJSON, opts...).ToFunc()
}

// ByMetadataJSON orders the results by the metadata_json field.
func ByMetadataJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataJSON, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}
