// Code generated by ent, DO NOT EDIT.

package inventory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/entregamais/platform/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldUpdatedAt, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldQuantity, v))
}

// ReservedQuantity applies equality check predicate on the "reserved_quantity" field. It's identical to ReservedQuantityEQ.
func ReservedQuantity(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldReservedQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldUpdatedAt, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldQuantity, v))
}

// ReservedQuantityEQ applies the EQ predicate on the "reserved_quantity" field.
func ReservedQuantityEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldReservedQuantity, v))
}

// ReservedQuantityNEQ applies the NEQ predicate on the "reserved_quantity" field.
func ReservedQuantityNEQ(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldReservedQuantity, v))
}

// ReservedQuantityIn applies the In predicate on the "reserved_quantity" field.
func ReservedQuantityIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldReservedQuantity, vs...))
}

// ReservedQuantityNotIn applies the NotIn predicate on the "reserved_quantity" field.
func ReservedQuantityNotIn(vs ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldReservedQuantity, vs...))
}

// ReservedQuantityGT applies the GT predicate on the "reserved_quantity" field.
func ReservedQuantityGT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldReservedQuantity, v))
}

// ReservedQuantityGTE applies the GTE predicate on the "reserved_quantity" field.
func ReservedQuantityGTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldReservedQuantity, v))
}

// ReservedQuantityLT applies the LT predicate on the "reserved_quantity" field.
func ReservedQuantityLT(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldReservedQuantity, v))
}

// ReservedQuantityLTE applies the LTE predicate on the "reserved_quantity" field.
func ReservedQuantityLTE(v int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldReservedQuantity, v))
}

// HasSeller applies the HasEdge predicate on the "seller" edge.
func HasSeller() predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SellerTable, SellerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSellerWith applies the HasEdge predicate on the "seller" edge with a given conditions (other predicates).
func HasSellerWith(preds ...predicate.Seller) predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := newSellerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.NotPredicates(p))
}
