// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/entregamais/platform/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTotalAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCurrency, v))
}

// DeliveryAddressJSON applies equality check predicate on the "delivery_address_json" field. It's identical to DeliveryAddressJSONEQ.
func DeliveryAddressJSON(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryAddressJSON, v))
}

// DeliveryLatitude applies equality check predicate on the "delivery_latitude" field. It's identical to DeliveryLatitudeEQ.
func DeliveryLatitude(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryLatitude, v))
}

// DeliveryLongitude applies equality check predicate on the "delivery_longitude" field. It's identical to DeliveryLongitudeEQ.
func DeliveryLongitude(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryLongitude, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAcceptedAt, v))
}

// DispatchedAt applies equality check predicate on the "dispatched_at" field. It's identical to DispatchedAtEQ.
func DispatchedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDispatchedAt, v))
}

// DeliveredAt applies equality check predicate on the "delivered_at" field. It's identical to DeliveredAtEQ.
func DeliveredAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldStatus, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTotalAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldCurrency, v))
}

// DeliveryAddressJSONEQ applies the EQ predicate on the "delivery_address_json" field.
func DeliveryAddressJSONEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONNEQ applies the NEQ predicate on the "delivery_address_json" field.
func DeliveryAddressJSONNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONIn applies the In predicate on the "delivery_address_json" field.
func DeliveryAddressJSONIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDeliveryAddressJSON, vs...))
}

// DeliveryAddressJSONNotIn applies the NotIn predicate on the "delivery_address_json" field.
func DeliveryAddressJSONNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDeliveryAddressJSON, vs...))
}

// DeliveryAddressJSONGT applies the GT predicate on the "delivery_address_json" field.
func DeliveryAddressJSONGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONGTE applies the GTE predicate on the "delivery_address_json" field.
func DeliveryAddressJSONGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONLT applies the LT predicate on the "delivery_address_json" field.
func DeliveryAddressJSONLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONLTE applies the LTE predicate on the "delivery_address_json" field.
func DeliveryAddressJSONLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONContains applies the Contains predicate on the "delivery_address_json" field.
func DeliveryAddressJSONContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONHasPrefix applies the HasPrefix predicate on the "delivery_address_json" field.
func DeliveryAddressJSONHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONHasSuffix applies the HasSuffix predicate on the "delivery_address_json" field.
func DeliveryAddressJSONHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONEqualFold applies the EqualFold predicate on the "delivery_address_json" field.
func DeliveryAddressJSONEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldDeliveryAddressJSON, v))
}

// DeliveryAddressJSONContainsFold applies the ContainsFold predicate on the "delivery_address_json" field.
func DeliveryAddressJSONContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldDeliveryAddressJSON, v))
}

// DeliveryLatitudeEQ applies the EQ predicate on the "delivery_latitude" field.
func DeliveryLatitudeEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeNEQ applies the NEQ predicate on the "delivery_latitude" field.
func DeliveryLatitudeNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeIn applies the In predicate on the "delivery_latitude" field.
func DeliveryLatitudeIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDeliveryLatitude, vs...))
}

// DeliveryLatitudeNotIn applies the NotIn predicate on the "delivery_latitude" field.
func DeliveryLatitudeNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDeliveryLatitude, vs...))
}

// DeliveryLatitudeGT applies the GT predicate on the "delivery_latitude" field.
func DeliveryLatitudeGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeGTE applies the GTE predicate on the "delivery_latitude" field.
func DeliveryLatitudeGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeLT applies the LT predicate on the "delivery_latitude" field.
func DeliveryLatitudeLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeLTE applies the LTE predicate on the "delivery_latitude" field.
func DeliveryLatitudeLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDeliveryLatitude, v))
}

// DeliveryLatitudeIsNil applies the IsNil predicate on the "delivery_latitude" field.
func DeliveryLatitudeIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDeliveryLatitude))
}

// DeliveryLatitudeNotNil applies the NotNil predicate on the "delivery_latitude" field.
func DeliveryLatitudeNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDeliveryLatitude))
}

// DeliveryLongitudeEQ applies the EQ predicate on the "delivery_longitude" field.
func DeliveryLongitudeEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeNEQ applies the NEQ predicate on the "delivery_longitude" field.
func DeliveryLongitudeNEQ(v float64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeIn applies the In predicate on the "delivery_longitude" field.
func DeliveryLongitudeIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDeliveryLongitude, vs...))
}

// DeliveryLongitudeNotIn applies the NotIn predicate on the "delivery_longitude" field.
func DeliveryLongitudeNotIn(vs ...float64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDeliveryLongitude, vs...))
}

// DeliveryLongitudeGT applies the GT predicate on the "delivery_longitude" field.
func DeliveryLongitudeGT(v float64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeGTE applies the GTE predicate on the "delivery_longitude" field.
func DeliveryLongitudeGTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeLT applies the LT predicate on the "delivery_longitude" field.
func DeliveryLongitudeLT(v float64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeLTE applies the LTE predicate on the "delivery_longitude" field.
func DeliveryLongitudeLTE(v float64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDeliveryLongitude, v))
}

// DeliveryLongitudeIsNil applies the IsNil predicate on the "delivery_longitude" field.
func DeliveryLongitudeIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDeliveryLongitude))
}

// DeliveryLongitudeNotNil applies the NotNil predicate on the "delivery_longitude" field.
func DeliveryLongitudeNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDeliveryLongitude))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAcceptedAt, v))
}

// AcceptedAtIsNil applies the IsNil predicate on the "accepted_at" field.
func AcceptedAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldAcceptedAt))
}

// AcceptedAtNotNil applies the NotNil predicate on the "accepted_at" field.
func AcceptedAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldAcceptedAt))
}

// DispatchedAtEQ applies the EQ predicate on the "dispatched_at" field.
func DispatchedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDispatchedAt, v))
}

// DispatchedAtNEQ applies the NEQ predicate on the "dispatched_at" field.
func DispatchedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDispatchedAt, v))
}

// DispatchedAtIn applies the In predicate on the "dispatched_at" field.
func DispatchedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDispatchedAt, vs...))
}

// DispatchedAtNotIn applies the NotIn predicate on the "dispatched_at" field.
func DispatchedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDispatchedAt, vs...))
}

// DispatchedAtGT applies the GT predicate on the "dispatched_at" field.
func DispatchedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDispatchedAt, v))
}

// DispatchedAtGTE applies the GTE predicate on the "dispatched_at" field.
func DispatchedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDispatchedAt, v))
}

// DispatchedAtLT applies the LT predicate on the "dispatched_at" field.
func DispatchedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDispatchedAt, v))
}

// DispatchedAtLTE applies the LTE predicate on the "dispatched_at" field.
func DispatchedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDispatchedAt, v))
}

// DispatchedAtIsNil applies the IsNil predicate on the "dispatched_at" field.
func DispatchedAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDispatchedAt))
}

// DispatchedAtNotNil applies the NotNil predicate on the "dispatched_at" field.
func DispatchedAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDispatchedAt))
}

// DeliveredAtEQ applies the EQ predicate on the "delivered_at" field.
func DeliveredAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDeliveredAt, v))
}

// DeliveredAtNEQ applies the NEQ predicate on the "delivered_at" field.
func DeliveredAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDeliveredAt, v))
}

// DeliveredAtIn applies the In predicate on the "delivered_at" field.
func DeliveredAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDeliveredAt, vs...))
}

// DeliveredAtNotIn applies the NotIn predicate on the "delivered_at" field.
func DeliveredAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDeliveredAt, vs...))
}

// DeliveredAtGT applies the GT predicate on the "delivered_at" field.
func DeliveredAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDeliveredAt, v))
}

// DeliveredAtGTE applies the GTE predicate on the "delivered_at" field.
func DeliveredAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDeliveredAt, v))
}

// DeliveredAtLT applies the LT predicate on the "delivered_at" field.
func DeliveredAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDeliveredAt, v))
}

// DeliveredAtLTE applies the LTE predicate on the "delivered_at" field.
func DeliveredAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDeliveredAt, v))
}

// DeliveredAtIsNil applies the IsNil predicate on the "delivered_at" field.
func DeliveredAtIsNil() predicate.Order {
	return predicate.Order(sql.FieldIsNull(FieldDeliveredAt))
}

// DeliveredAtNotNil applies the NotNil predicate on the "delivered_at" field.
func DeliveredAtNotNil() predicate.Order {
	return predicate.Order(sql.FieldNotNull(FieldDeliveredAt))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.User) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeller applies the HasEdge predicate on the "seller" edge.
func HasSeller() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SellerTable, SellerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSellerWith applies the HasEdge predicate on the "seller" edge with a given conditions (other predicates).
func HasSellerWith(preds ...predicate.Seller) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newSellerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDriver applies the HasEdge predicate on the "driver" edge.
func HasDriver() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DriverTable, DriverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDriverWith applies the HasEdge predicate on the "driver" edge with a given conditions (other predicates).
func HasDriverWith(preds ...predicate.Entregador) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newDriverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.OrderItem) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStatusHistory applies the HasEdge predicate on the "status_history" edge.
func HasStatusHistory() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatusHistoryTable, StatusHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatusHistoryWith applies the HasEdge predicate on the "status_history" edge with a given conditions (other predicates).
func HasStatusHistoryWith(preds ...predicate.OrderStatusHistory) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newStatusHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPayments applies the HasEdge predicate on the "payments" edge.
func HasPayments() predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentsWith applies the HasEdge predicate on the "payments" edge with a given conditions (other predicates).
func HasPaymentsWith(preds ...predicate.Payment) predicate.Order {
	return predicate.Order(func(s *sql.Selector) {
		step := newPaymentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
