apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: entregamais
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: entregamais/backend:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/v1/ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/live
              port: 8080
