// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/address"
	"github.com/entregamais/platform/backend/ent/user"
)

// AddressCreate is the builder for creating a Address entity.
type AddressCreate struct {
	config
	mutation *AddressMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AddressCreate) SetCreatedAt(v time.Time) *AddressCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AddressCreate) SetNillableCreatedAt(v *time.Time) *AddressCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AddressCreate) SetUpdatedAt(v time.Time) *AddressCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AddressCreate) SetNillableUpdatedAt(v *time.Time) *AddressCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *AddressCreate) SetLabel(v string) *AddressCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *AddressCreate) SetNillableLabel(v *string) *AddressCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetStreet sets the "street" field.
func (_c *AddressCreate) SetStreet(v string) *AddressCreate {
	_c.mutation.SetStreet(v)
	return _c
}

// SetNumber sets the "number" field.
func (_c *AddressCreate) SetNumber(v string) *AddressCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetDistrict sets the "district" field.
func (_c *AddressCreate) SetDistrict(v string) *AddressCreate {
	_c.mutation.SetDistrict(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *AddressCreate) SetCity(v string) *AddressCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetState sets the "state" field.
func (_c *AddressCreate) SetState(v string) *AddressCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetZipCode sets the "zip_code" field.
func (_c *AddressCreate) SetZipCode(v string) *AddressCreate {
	_c.mutation.SetZipCode(v)
	return _c
}

// SetLat sets the "lat" field.
func (_c *AddressCreate) SetLat(v float64) *AddressCreate {
	_c.mutation.SetLat(v)
	return _c
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_c *AddressCreate) SetNillableLat(v *float64) *AddressCreate {
	if v != nil {
		_c.SetLat(*v)
	}
	return _c
}

// SetLng sets the "lng" field.
func (_c *AddressCreate) SetLng(v float64) *AddressCreate {
	_c.mutation.SetLng(v)
	return _c
}

// SetNillableLng sets the "lng" field if the given value is not nil.
func (_c *AddressCreate) SetNillableLng(v *float64) *AddressCreate {
	if v != nil {
		_c.SetLng(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AddressCreate) SetID(v string) *AddressCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AddressCreate) SetUserID(id string) *AddressCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AddressCreate) SetUser(v *User) *AddressCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_c *AddressCreate) Mutation() *AddressMutation {
	return _c.mutation
}

// Save creates the Address in the database.
func (_c *AddressCreate) Save(ctx context.Context) (*Address, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AddressCreate) SaveX(ctx context.Context) *Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AddressCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := address.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := address.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Label(); !ok {
		v := address.DefaultLabel
		_c.mutation.SetLabel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AddressCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Address.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Address.updated_at"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Address.label"`)}
	}
	if _, ok := _c.mutation.Street(); !ok {
		return &ValidationError{Name: "street", err: errors.New(`ent: missing required field "Address.street"`)}
	}
	if v, ok := _c.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Address.number"`)}
	}
	if v, ok := _c.mutation.Number(); ok {
		if err := address.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Address.number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.District(); !ok {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required field "Address.district"`)}
	}
	if v, ok := _c.mutation.District(); ok {
		if err := address.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "Address.district": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Address.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Address.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := address.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Address.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ZipCode(); !ok {
		return &ValidationError{Name: "zip_code", err: errors.New(`ent: missing required field "Address.zip_code"`)}
	}
	if v, ok := _c.mutation.ZipCode(); ok {
		if err := address.ZipCodeValidator(v); err != nil {
			return &ValidationError{Name: "zip_code", err: fmt.Errorf(`ent: validator failed for field "Address.zip_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := address.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Address.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Address.user"`)}
	}
	return nil
}

func (_c *AddressCreate) sqlSave(ctx context.Context) (*Address, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Address.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AddressCreate) createSpec() (*Address, *sqlgraph.CreateSpec) {
	var (
		_node = &Address{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(address.Table, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(address.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(address.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
		_node.Street = value
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(address.FieldNumber, field.TypeString, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.District(); ok {
		_spec.SetField(address.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(address.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.ZipCode(); ok {
		_spec.SetField(address.FieldZipCode, field.TypeString, value)
		_node.ZipCode = value
	}
	if value, ok := _c.mutation.Lat(); ok {
		_spec.SetField(address.FieldLat, field.TypeFloat64, value)
		_node.Lat = value
	}
	if value, ok := _c.mutation.Lng(); ok {
		_spec.SetField(address.FieldLng, field.TypeFloat64, value)
		_node.Lng = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.UserTable,
			Columns: []string{address.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_addresses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AddressCreateBulk is the builder for creating many Address entities in bulk.
type AddressCreateBulk struct {
	config
	err      error
	builders []*AddressCreate
}

// Save creates the Address entities in the database.
func (_c *AddressCreateBulk) Save(ctx context.Context) ([]*Address, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Address, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AddressCreateBulk) SaveX(ctx context.Context) []*Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
