// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/entregador"
	"github.com/entregamais/platform/backend/ent/order"
	"github.com/entregamais/platform/backend/ent/orderitem"
	"github.com/entregamais/platform/backend/ent/orderstatushistory"
	"github.com/entregamais/platform/backend/ent/payment"
	"github.com/entregamais/platform/backend/ent/predicate"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/user"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdate) SetTotalAmount(v float64) *OrderUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTotalAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdate) AddTotalAmount(v float64) *OrderUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *OrderUpdate) SetCurrency(v string) *OrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCurrency(v *string) *OrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDeliveryAddressJSON sets the "delivery_address_json" field.
func (_u *OrderUpdate) SetDeliveryAddressJSON(v string) *OrderUpdate {
	_u.mutation.SetDeliveryAddressJSON(v)
	return _u
}

// SetNillableDeliveryAddressJSON sets the "delivery_address_json" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeliveryAddressJSON(v *string) *OrderUpdate {
	if v != nil {
		_u.SetDeliveryAddressJSON(*v)
	}
	return _u
}

// SetDeliveryLatitude sets the "delivery_latitude" field.
func (_u *OrderUpdate) SetDeliveryLatitude(v float64) *OrderUpdate {
	_u.mutation.ResetDeliveryLatitude()
	_u.mutation.SetDeliveryLatitude(v)
	return _u
}

// SetNillableDeliveryLatitude sets the "delivery_latitude" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeliveryLatitude(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetDeliveryLatitude(*v)
	}
	return _u
}

// AddDeliveryLatitude adds value to the "delivery_latitude" field.
func (_u *OrderUpdate) AddDeliveryLatitude(v float64) *OrderUpdate {
	_u.mutation.AddDeliveryLatitude(v)
	return _u
}

// ClearDeliveryLatitude clears the value of the "delivery_latitude" field.
func (_u *OrderUpdate) ClearDeliveryLatitude() *OrderUpdate {
	_u.mutation.ClearDeliveryLatitude()
	return _u
}

// SetDeliveryLongitude sets the "delivery_longitude" field.
func (_u *OrderUpdate) SetDeliveryLongitude(v float64) *OrderUpdate {
	_u.mutation.ResetDeliveryLongitude()
	_u.mutation.SetDeliveryLongitude(v)
	return _u
}

// SetNillableDeliveryLongitude sets the "delivery_longitude" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeliveryLongitude(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetDeliveryLongitude(*v)
	}
	return _u
}

// AddDeliveryLongitude adds value to the "delivery_longitude" field.
func (_u *OrderUpdate) AddDeliveryLongitude(v float64) *OrderUpdate {
	_u.mutation.AddDeliveryLongitude(v)
	return _u
}

// ClearDeliveryLongitude clears the value of the "delivery_longitude" field.
func (_u *OrderUpdate) ClearDeliveryLongitude() *OrderUpdate {
	_u.mutation.ClearDeliveryLongitude()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *OrderUpdate) SetAcceptedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAcceptedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *OrderUpdate) ClearAcceptedAt() *OrderUpdate {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *OrderUpdate) SetDispatchedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDispatchedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *OrderUpdate) ClearDispatchedAt() *OrderUpdate {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *OrderUpdate) SetDeliveredAt(v time.Time) *OrderUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableDeliveredAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *OrderUpdate) ClearDeliveredAt() *OrderUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetCustomerID sets the "customer" edge to the User entity by ID.
func (_u *OrderUpdate) SetCustomerID(id string) *OrderUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the User entity.
func (_u *OrderUpdate) SetCustomer(v *User) *OrderUpdate {
	return _u.SetCustomerID(v.ID)
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *OrderUpdate) SetSellerID(id string) *OrderUpdate {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *OrderUpdate) SetSeller(v *Seller) *OrderUpdate {
	return _u.SetSellerID(v.ID)
}

// SetDriverID sets the "driver" edge to the Entregador entity by ID.
func (_u *OrderUpdate) SetDriverID(id string) *OrderUpdate {
	_u.mutation.SetDriverID(id)
	return _u
}

// SetNillableDriverID sets the "driver" edge to the Entregador entity by ID if the given value is not nil.
func (_u *OrderUpdate) SetNillableDriverID(id *string) *OrderUpdate {
	if id != nil {
		_u = _u.SetDriverID(*id)
	}
	return _u
}

// SetDriver sets the "driver" edge to the Entregador entity.
func (_u *OrderUpdate) SetDriver(v *Entregador) *OrderUpdate {
	return _u.SetDriverID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdate) AddItemIDs(ids ...string) *OrderUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdate) AddItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddStatusHistoryIDs adds the "status_history" edge to the OrderStatusHistory entity by IDs.
func (_u *OrderUpdate) AddStatusHistoryIDs(ids ...string) *OrderUpdate {
	_u.mutation.AddStatusHistoryIDs(ids...)
	return _u
}

// AddStatusHistory adds the "status_history" edges to the OrderStatusHistory entity.
func (_u *OrderUpdate) AddStatusHistory(v ...*OrderStatusHistory) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusHistoryIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *OrderUpdate) AddPaymentIDs(ids ...string) *OrderUpdate {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *OrderUpdate) AddPayments(v ...*Payment) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the User entity.
func (_u *OrderUpdate) ClearCustomer() *OrderUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *OrderUpdate) ClearSeller() *OrderUpdate {
	_u.mutation.ClearSeller()
	return _u
}

// ClearDriver clears the "driver" edge to the Entregador entity.
func (_u *OrderUpdate) ClearDriver() *OrderUpdate {
	_u.mutation.ClearDriver()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdate) ClearItems() *OrderUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdate) RemoveItemIDs(ids ...string) *OrderUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdate) RemoveItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearStatusHistory clears all "status_history" edges to the OrderStatusHistory entity.
func (_u *OrderUpdate) ClearStatusHistory() *OrderUpdate {
	_u.mutation.ClearStatusHistory()
	return _u
}

// RemoveStatusHistoryIDs removes the "status_history" edge to OrderStatusHistory entities by IDs.
func (_u *OrderUpdate) RemoveStatusHistoryIDs(ids ...string) *OrderUpdate {
	_u.mutation.RemoveStatusHistoryIDs(ids...)
	return _u
}

// RemoveStatusHistory removes "status_history" edges to OrderStatusHistory entities.
func (_u *OrderUpdate) RemoveStatusHistory(v ...*OrderStatusHistory) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusHistoryIDs(ids...)
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *OrderUpdate) ClearPayments() *OrderUpdate {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *OrderUpdate) RemovePaymentIDs(ids ...string) *OrderUpdate {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *OrderUpdate) RemovePayments(v ...*Payment) *OrderUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.TotalAmount(); ok {
		if err := order.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "Order.total_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryAddressJSON(); ok {
		if err := order.DeliveryAddressJSONValidator(v); err != nil {
			return &ValidationError{Name: "delivery_address_json", err: fmt.Errorf(`ent: validator failed for field "Order.delivery_address_json": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.customer"`)
	}
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.seller"`)
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(order.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryAddressJSON(); ok {
		_spec.SetField(order.FieldDeliveryAddressJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryLatitude(); ok {
		_spec.SetField(order.FieldDeliveryLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryLatitude(); ok {
		_spec.AddField(order.FieldDeliveryLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.DeliveryLatitudeCleared() {
		_spec.ClearField(order.FieldDeliveryLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DeliveryLongitude(); ok {
		_spec.SetField(order.FieldDeliveryLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryLongitude(); ok {
		_spec.AddField(order.FieldDeliveryLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.DeliveryLongitudeCleared() {
		_spec.ClearField(order.FieldDeliveryLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(order.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(order.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(order.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(order.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(order.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(order.FieldDeliveredAt, field.TypeTime)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.CustomerTable,
			Columns: []string{order.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.CustomerTable,
			Columns: []string{order.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.SellerTable,
			Columns: []string{order.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.SellerTable,
			Columns: []string{order.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DriverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.DriverTable,
			Columns: []string{order.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entregador.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DriverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.DriverTable,
			Columns: []string{order.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entregador.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusHistoryIDs(); len(nodes) > 0 && !_u.mutation.StatusHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdateOne) SetTotalAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTotalAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdateOne) AddTotalAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *OrderUpdateOne) SetCurrency(v string) *OrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCurrency(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDeliveryAddressJSON sets the "delivery_address_json" field.
func (_u *OrderUpdateOne) SetDeliveryAddressJSON(v string) *OrderUpdateOne {
	_u.mutation.SetDeliveryAddressJSON(v)
	return _u
}

// SetNillableDeliveryAddressJSON sets the "delivery_address_json" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeliveryAddressJSON(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetDeliveryAddressJSON(*v)
	}
	return _u
}

// SetDeliveryLatitude sets the "delivery_latitude" field.
func (_u *OrderUpdateOne) SetDeliveryLatitude(v float64) *OrderUpdateOne {
	_u.mutation.ResetDeliveryLatitude()
	_u.mutation.SetDeliveryLatitude(v)
	return _u
}

// SetNillableDeliveryLatitude sets the "delivery_latitude" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeliveryLatitude(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetDeliveryLatitude(*v)
	}
	return _u
}

// AddDeliveryLatitude adds value to the "delivery_latitude" field.
func (_u *OrderUpdateOne) AddDeliveryLatitude(v float64) *OrderUpdateOne {
	_u.mutation.AddDeliveryLatitude(v)
	return _u
}

// ClearDeliveryLatitude clears the value of the "delivery_latitude" field.
func (_u *OrderUpdateOne) ClearDeliveryLatitude() *OrderUpdateOne {
	_u.mutation.ClearDeliveryLatitude()
	return _u
}

// SetDeliveryLongitude sets the "delivery_longitude" field.
func (_u *OrderUpdateOne) SetDeliveryLongitude(v float64) *OrderUpdateOne {
	_u.mutation.ResetDeliveryLongitude()
	_u.mutation.SetDeliveryLongitude(v)
	return _u
}

// SetNillableDeliveryLongitude sets the "delivery_longitude" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeliveryLongitude(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetDeliveryLongitude(*v)
	}
	return _u
}

// AddDeliveryLongitude adds value to the "delivery_longitude" field.
func (_u *OrderUpdateOne) AddDeliveryLongitude(v float64) *OrderUpdateOne {
	_u.mutation.AddDeliveryLongitude(v)
	return _u
}

// ClearDeliveryLongitude clears the value of the "delivery_longitude" field.
func (_u *OrderUpdateOne) ClearDeliveryLongitude() *OrderUpdateOne {
	_u.mutation.ClearDeliveryLongitude()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *OrderUpdateOne) SetAcceptedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAcceptedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *OrderUpdateOne) ClearAcceptedAt() *OrderUpdateOne {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetDispatchedAt sets the "dispatched_at" field.
func (_u *OrderUpdateOne) SetDispatchedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetDispatchedAt(v)
	return _u
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDispatchedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetDispatchedAt(*v)
	}
	return _u
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (_u *OrderUpdateOne) ClearDispatchedAt() *OrderUpdateOne {
	_u.mutation.ClearDispatchedAt()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *OrderUpdateOne) SetDeliveredAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDeliveredAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *OrderUpdateOne) ClearDeliveredAt() *OrderUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetCustomerID sets the "customer" edge to the User entity by ID.
func (_u *OrderUpdateOne) SetCustomerID(id string) *OrderUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the User entity.
func (_u *OrderUpdateOne) SetCustomer(v *User) *OrderUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *OrderUpdateOne) SetSellerID(id string) *OrderUpdateOne {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *OrderUpdateOne) SetSeller(v *Seller) *OrderUpdateOne {
	return _u.SetSellerID(v.ID)
}

// SetDriverID sets the "driver" edge to the Entregador entity by ID.
func (_u *OrderUpdateOne) SetDriverID(id string) *OrderUpdateOne {
	_u.mutation.SetDriverID(id)
	return _u
}

// SetNillableDriverID sets the "driver" edge to the Entregador entity by ID if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableDriverID(id *string) *OrderUpdateOne {
	if id != nil {
		_u = _u.SetDriverID(*id)
	}
	return _u
}

// SetDriver sets the "driver" edge to the Entregador entity.
func (_u *OrderUpdateOne) SetDriver(v *Entregador) *OrderUpdateOne {
	return _u.SetDriverID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdateOne) AddItemIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) AddItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddStatusHistoryIDs adds the "status_history" edge to the OrderStatusHistory entity by IDs.
func (_u *OrderUpdateOne) AddStatusHistoryIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.AddStatusHistoryIDs(ids...)
	return _u
}

// AddStatusHistory adds the "status_history" edges to the OrderStatusHistory entity.
func (_u *OrderUpdateOne) AddStatusHistory(v ...*OrderStatusHistory) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusHistoryIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *OrderUpdateOne) AddPaymentIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *OrderUpdateOne) AddPayments(v ...*Payment) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the User entity.
func (_u *OrderUpdateOne) ClearCustomer() *OrderUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *OrderUpdateOne) ClearSeller() *OrderUpdateOne {
	_u.mutation.ClearSeller()
	return _u
}

// ClearDriver clears the "driver" edge to the Entregador entity.
func (_u *OrderUpdateOne) ClearDriver() *OrderUpdateOne {
	_u.mutation.ClearDriver()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) ClearItems() *OrderUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdateOne) RemoveItemIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdateOne) RemoveItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearStatusHistory clears all "status_history" edges to the OrderStatusHistory entity.
func (_u *OrderUpdateOne) ClearStatusHistory() *OrderUpdateOne {
	_u.mutation.ClearStatusHistory()
	return _u
}

// RemoveStatusHistoryIDs removes the "status_history" edge to OrderStatusHistory entities by IDs.
func (_u *OrderUpdateOne) RemoveStatusHistoryIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.RemoveStatusHistoryIDs(ids...)
	return _u
}

// RemoveStatusHistory removes "status_history" edges to OrderStatusHistory entities.
func (_u *OrderUpdateOne) RemoveStatusHistory(v ...*OrderStatusHistory) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusHistoryIDs(ids...)
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *OrderUpdateOne) ClearPayments() *OrderUpdateOne {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *OrderUpdateOne) RemovePaymentIDs(ids ...string) *OrderUpdateOne {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *OrderUpdateOne) RemovePayments(v ...*Payment) *OrderUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.TotalAmount(); ok {
		if err := order.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "Order.total_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryAddressJSON(); ok {
		if err := order.DeliveryAddressJSONValidator(v); err != nil {
			return &ValidationError{Name: "delivery_address_json", err: fmt.Errorf(`ent: validator failed for field "Order.delivery_address_json": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.customer"`)
	}
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.seller"`)
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(order.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryAddressJSON(); ok {
		_spec.SetField(order.FieldDeliveryAddressJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryLatitude(); ok {
		_spec.SetField(order.FieldDeliveryLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryLatitude(); ok {
		_spec.AddField(order.FieldDeliveryLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.DeliveryLatitudeCleared() {
		_spec.ClearField(order.FieldDeliveryLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DeliveryLongitude(); ok {
		_spec.SetField(order.FieldDeliveryLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryLongitude(); ok {
		_spec.AddField(order.FieldDeliveryLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.DeliveryLongitudeCleared() {
		_spec.ClearField(order.FieldDeliveryLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(order.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(order.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DispatchedAt(); ok {
		_spec.SetField(order.FieldDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.DispatchedAtCleared() {
		_spec.ClearField(order.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(order.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(order.FieldDeliveredAt, field.TypeTime)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.CustomerTable,
			Columns: []string{order.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.CustomerTable,
			Columns: []string{order.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.SellerTable,
			Columns: []string{order.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.SellerTable,
			Columns: []string{order.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DriverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.DriverTable,
			Columns: []string{order.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entregador.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DriverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.DriverTable,
			Columns: []string{order.DriverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entregador.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusHistoryIDs(); len(nodes) > 0 && !_u.mutation.StatusHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.StatusHistoryTable,
			Columns: []string{order.StatusHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.PaymentsTable,
			Columns: []string{order.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
