// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/outboxevent"
	"github.com/entregamais/platform/backend/ent/predicate"
)

// OutboxEventUpdate is the builder for updating OutboxEvent entities.
type OutboxEventUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxEventMutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdate) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdate) SetUpdatedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxEventUpdate) SetAggregateType(v string) *OutboxEventUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableAggregateType(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxEventUpdate) SetAggregateID(v string) *OutboxEventUpdate {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableAggregateID(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxEventUpdate) SetEventType(v string) *OutboxEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableEventType(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEventVersion sets the "event_version" field.
func (_u *OutboxEventUpdate) SetEventVersion(v string) *OutboxEventUpdate {
	_u.mutation.SetEventVersion(v)
	return _u
}

// SetNillableEventVersion sets the "event_version" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableEventVersion(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetEventVersion(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *OutboxEventUpdate) SetPayloadJSON(v string) *OutboxEventUpdate {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillablePayloadJSON(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *OutboxEventUpdate) SetMetadataJSON(v string) *OutboxEventUpdate {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableMetadataJSON(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *OutboxEventUpdate) ClearMetadataJSON() *OutboxEventUpdate {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxEventUpdate) SetStatus(v string) *OutboxEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableStatus(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *OutboxEventUpdate) SetRetryCount(v int) *OutboxEventUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableRetryCount(v *int) *OutboxEventUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *OutboxEventUpdate) AddRetryCount(v int) *OutboxEventUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboxEventUpdate) SetNextAttemptAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableNextAttemptAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxEventUpdate) SetPublishedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillablePublishedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxEventUpdate) ClearPublishedAt() *OutboxEventUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdate) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxEventUpdate) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := outboxevent.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := outboxevent.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := outboxevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadJSON(); ok {
		if err := outboxevent.PayloadJSONValidator(v); err != nil {
			return &ValidationError{Name: "payload_json", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.payload_json": %w`, err)}
		}
	}
	return nil
}

func (_u *OutboxEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outboxevent.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outboxevent.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventVersion(); ok {
		_spec.SetField(outboxevent.FieldEventVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(outboxevent.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(outboxevent.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(outboxevent.FieldMetadataJSON, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(outboxevent.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(outboxevent.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboxevent.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outboxevent.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxEventUpdateOne is the builder for updating a single OutboxEvent entity.
type OutboxEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OutboxEventUpdateOne) SetUpdatedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxEventUpdateOne) SetAggregateType(v string) *OutboxEventUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableAggregateType(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxEventUpdateOne) SetAggregateID(v string) *OutboxEventUpdateOne {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableAggregateID(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxEventUpdateOne) SetEventType(v string) *OutboxEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableEventType(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetEventVersion sets the "event_version" field.
func (_u *OutboxEventUpdateOne) SetEventVersion(v string) *OutboxEventUpdateOne {
	_u.mutation.SetEventVersion(v)
	return _u
}

// SetNillableEventVersion sets the "event_version" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableEventVersion(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetEventVersion(*v)
	}
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *OutboxEventUpdateOne) SetPayloadJSON(v string) *OutboxEventUpdateOne {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillablePayloadJSON(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *OutboxEventUpdateOne) SetMetadataJSON(v string) *OutboxEventUpdateOne {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// SetNillableMetadataJSON sets the "metadata_json" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableMetadataJSON(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetMetadataJSON(*v)
	}
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *OutboxEventUpdateOne) ClearMetadataJSON() *OutboxEventUpdateOne {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OutboxEventUpdateOne) SetStatus(v string) *OutboxEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableStatus(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *OutboxEventUpdateOne) SetRetryCount(v int) *OutboxEventUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableRetryCount(v *int) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *OutboxEventUpdateOne) AddRetryCount(v int) *OutboxEventUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboxEventUpdateOne) SetNextAttemptAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableNextAttemptAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxEventUpdateOne) SetPublishedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillablePublishedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxEventUpdateOne) ClearPublishedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdateOne) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdateOne) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxEventUpdateOne) Select(field string, fields ...string) *OutboxEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboxEvent entity.
func (_u *OutboxEventUpdateOne) Save(ctx context.Context) (*OutboxEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) SaveX(ctx context.Context) *OutboxEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OutboxEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := outboxevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OutboxEventUpdateOne) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := outboxevent.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := outboxevent.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := outboxevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadJSON(); ok {
		if err := outboxevent.PayloadJSONValidator(v); err != nil {
			return &ValidationError{Name: "payload_json", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.payload_json": %w`, err)}
		}
	}
	return nil
}

func (_u *OutboxEventUpdateOne) sqlSave(ctx context.Context) (_node *OutboxEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxevent.FieldID)
		for _, f := range fields {
			if !outboxevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outboxevent.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outboxevent.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventVersion(); ok {
		_spec.SetField(outboxevent.FieldEventVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(outboxevent.FieldPayloadJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(outboxevent.FieldMetadataJSON, field.TypeString, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(outboxevent.FieldMetadataJSON, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(outboxevent.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(outboxevent.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboxevent.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outboxevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outboxevent.FieldPublishedAt, field.TypeTime)
	}
	_node = &OutboxEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
