// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/entregamais/platform/backend/ent/address"
	"github.com/entregamais/platform/backend/ent/asset"
	"github.com/entregamais/platform/backend/ent/auditlog"
	"github.com/entregamais/platform/backend/ent/cart"
	"github.com/entregamais/platform/backend/ent/cartitem"
	"github.com/entregamais/platform/backend/ent/category"
	"github.com/entregamais/platform/backend/ent/entregador"
	"github.com/entregamais/platform/backend/ent/inventory"
	"github.com/entregamais/platform/backend/ent/order"
	"github.com/entregamais/platform/backend/ent/orderitem"
	"github.com/entregamais/platform/backend/ent/orderstatushistory"
	"github.com/entregamais/platform/backend/ent/outboxevent"
	"github.com/entregamais/platform/backend/ent/payment"
	"github.com/entregamais/platform/backend/ent/product"
	"github.com/entregamais/platform/backend/ent/productimage"
	"github.com/entregamais/platform/backend/ent/schema"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/selleruser"
	"github.com/entregamais/platform/backend/ent/upload"
	"github.com/entregamais/platform/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressMixin := schema.Address{}.Mixin()
	addressMixinFields0 := addressMixin[0].Fields()
	_ = addressMixinFields0
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescCreatedAt is the schema descriptor for created_at field.
	addressDescCreatedAt := addressMixinFields0[0].Descriptor()
	// address.DefaultCreatedAt holds the default value on creation for the created_at field.
	address.DefaultCreatedAt = addressDescCreatedAt.Default.(func() time.Time)
	// addressDescUpdatedAt is the schema descriptor for updated_at field.
	addressDescUpdatedAt := addressMixinFields0[1].Descriptor()
	// address.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	address.DefaultUpdatedAt = addressDescUpdatedAt.Default.(func() time.Time)
	// address.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	address.UpdateDefaultUpdatedAt = addressDescUpdatedAt.UpdateDefault.(func() time.Time)
	// addressDescLabel is the schema descriptor for label field.
	addressDescLabel := addressFields[1].Descriptor()
	// address.DefaultLabel holds the default value on creation for the label field.
	address.DefaultLabel = addressDescLabel.Default.(string)
	// addressDescStreet is the schema descriptor for street field.
	addressDescStreet := addressFields[2].Descriptor()
	// address.StreetValidator is a validator for the "street" field. It is called by the builders before save.
	address.StreetValidator = addressDescStreet.Validators[0].(func(string) error)
	// addressDescNumber is the schema descriptor for number field.
	addressDescNumber := addressFields[3].Descriptor()
	// address.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	address.NumberValidator = addressDescNumber.Validators[0].(func(string) error)
	// addressDescDistrict is the schema descriptor for district field.
	addressDescDistrict := addressFields[4].Descriptor()
	// address.DistrictValidator is a validator for the "district" field. It is called by the builders before save.
	address.DistrictValidator = addressDescDistrict.Validators[0].(func(string) error)
	// addressDescCity is the schema descriptor for city field.
	addressDescCity := addressFields[5].Descriptor()
	// address.CityValidator is a validator for the "city" field. It is called by the builders before save.
	address.CityValidator = addressDescCity.Validators[0].(func(string) error)
	// addressDescState is the schema descriptor for state field.
	addressDescState := addressFields[6].Descriptor()
	// address.StateValidator is a validator for the "state" field. It is called by the builders before save.
	address.StateValidator = addressDescState.Validators[0].(func(string) error)
	// addressDescZipCode is the schema descriptor for zip_code field.
	addressDescZipCode := addressFields[7].Descriptor()
	// address.ZipCodeValidator is a validator for the "zip_code" field. It is called by the builders before save.
	address.ZipCodeValidator = addressDescZipCode.Validators[0].(func(string) error)
	// addressDescID is the schema descriptor for id field.
	addressDescID := addressFields[0].Descriptor()
	// address.IDValidator is a validator for the "id" field. It is called by the builders before save.
	address.IDValidator = addressDescID.Validators[0].(func(string) error)
	assetMixin := schema.Asset{}.Mixin()
	assetMixinFields0 := assetMixin[0].Fields()
	_ = assetMixinFields0
	assetFields := schema.Asset{}.Fields()
	_ = assetFields
	// assetDescCreatedAt is the schema descriptor for created_at field.
	assetDescCreatedAt := assetMixinFields0[0].Descriptor()
	// asset.DefaultCreatedAt holds the default value on creation for the created_at field.
	asset.DefaultCreatedAt = assetDescCreatedAt.Default.(func() time.Time)
	// assetDescUpdatedAt is the schema descriptor for updated_at field.
	assetDescUpdatedAt := assetMixinFields0[1].Descriptor()
	// asset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	asset.DefaultUpdatedAt = assetDescUpdatedAt.Default.(func() time.Time)
	// asset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	asset.UpdateDefaultUpdatedAt = assetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// assetDescBucket is the schema descriptor for bucket field.
	assetDescBucket := assetFields[1].Descriptor()
	// asset.BucketValidator is a validator for the "bucket" field. It is called by the builders before save.
	asset.BucketValidator = assetDescBucket.Validators[0].(func(string) error)
	// assetDescObjectKey is the schema descriptor for object_key field.
	assetDescObjectKey := assetFields[2].Descriptor()
	// asset.ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	asset.ObjectKeyValidator = assetDescObjectKey.Validators[0].(func(string) error)
	// assetDescContentType is the schema descriptor for content_type field.
	assetDescContentType := assetFields[3].Descriptor()
	// asset.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	asset.ContentTypeValidator = assetDescContentType.Validators[0].(func(string) error)
	// assetDescSizeBytes is the schema descriptor for size_bytes field.
	assetDescSizeBytes := assetFields[4].Descriptor()
	// asset.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	asset.SizeBytesValidator = assetDescSizeBytes.Validators[0].(func(int64) error)
	// assetDescStatus is the schema descriptor for status field.
	assetDescStatus := assetFields[6].Descriptor()
	// asset.DefaultStatus holds the default value on creation for the status field.
	asset.DefaultStatus = assetDescStatus.Default.(string)
	// assetDescID is the schema descriptor for id field.
	assetDescID := assetFields[0].Descriptor()
	// asset.IDValidator is a validator for the "id" field. It is called by the builders before save.
	asset.IDValidator = assetDescID.Validators[0].(func(string) error)
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields0[1].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescResourceType is the schema descriptor for resource_type field.
	auditlogDescResourceType := auditlogFields[3].Descriptor()
	// auditlog.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	auditlog.ResourceTypeValidator = auditlogDescResourceType.Validators[0].(func(string) error)
	// auditlogDescResourceID is the schema descriptor for resource_id field.
	auditlogDescResourceID := auditlogFields[4].Descriptor()
	// auditlog.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	auditlog.ResourceIDValidator = auditlogDescResourceID.Validators[0].(func(string) error)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditlog.IDValidator = auditlogDescID.Validators[0].(func(string) error)
	cartMixin := schema.Cart{}.Mixin()
	cartMixinFields0 := cartMixin[0].Fields()
	_ = cartMixinFields0
	cartFields := schema.Cart{}.Fields()
	_ = cartFields
	// cartDescCreatedAt is the schema descriptor for created_at field.
	cartDescCreatedAt := cartMixinFields0[0].Descriptor()
	// cart.DefaultCreatedAt holds the default value on creation for the created_at field.
	cart.DefaultCreatedAt = cartDescCreatedAt.Default.(func() time.Time)
	// cartDescUpdatedAt is the schema descriptor for updated_at field.
	cartDescUpdatedAt := cartMixinFields0[1].Descriptor()
	// cart.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cart.DefaultUpdatedAt = cartDescUpdatedAt.Default.(func() time.Time)
	// cart.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cart.UpdateDefaultUpdatedAt = cartDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartDescStatus is the schema descriptor for status field.
	cartDescStatus := cartFields[2].Descriptor()
	// cart.DefaultStatus holds the default value on creation for the status field.
	cart.DefaultStatus = cartDescStatus.Default.(string)
	// cartDescID is the schema descriptor for id field.
	cartDescID := cartFields[0].Descriptor()
	// cart.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cart.IDValidator = cartDescID.Validators[0].(func(string) error)
	cartitemMixin := schema.CartItem{}.Mixin()
	cartitemMixinFields0 := cartitemMixin[0].Fields()
	_ = cartitemMixinFields0
	cartitemFields := schema.CartItem{}.Fields()
	_ = cartitemFields
	// cartitemDescCreatedAt is the schema descriptor for created_at field.
	cartitemDescCreatedAt := cartitemMixinFields0[0].Descriptor()
	// cartitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	cartitem.DefaultCreatedAt = cartitemDescCreatedAt.Default.(func() time.Time)
	// cartitemDescUpdatedAt is the schema descriptor for updated_at field.
	cartitemDescUpdatedAt := cartitemMixinFields0[1].Descriptor()
	// cartitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cartitem.DefaultUpdatedAt = cartitemDescUpdatedAt.Default.(func() time.Time)
	// cartitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cartitem.UpdateDefaultUpdatedAt = cartitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cartitemDescQuantity is the schema descriptor for quantity field.
	cartitemDescQuantity := cartitemFields[1].Descriptor()
	// cartitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	cartitem.QuantityValidator = cartitemDescQuantity.Validators[0].(func(int) error)
	// cartitemDescUnitPrice is the schema descriptor for unit_price field.
	cartitemDescUnitPrice := cartitemFields[2].Descriptor()
	// cartitem.UnitPriceValidator is a validator for the "unit_price" field. It is called by the builders before save.
	cartitem.UnitPriceValidator = cartitemDescUnitPrice.Validators[0].(func(float64) error)
	// cartitemDescID is the schema descriptor for id field.
	cartitemDescID := cartitemFields[0].Descriptor()
	// cartitem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	cartitem.IDValidator = cartitemDescID.Validators[0].(func(string) error)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryFields[3].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(string)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.IDValidator is a validator for the "id" field. It is called by the builders before save.
	category.IDValidator = categoryDescID.Validators[0].(func(string) error)
	entregadorMixin := schema.Entregador{}.Mixin()
	entregadorMixinFields0 := entregadorMixin[0].Fields()
	_ = entregadorMixinFields0
	entregadorFields := schema.Entregador{}.Fields()
	_ = entregadorFields
	// entregadorDescCreatedAt is the schema descriptor for created_at field.
	entregadorDescCreatedAt := entregadorMixinFields0[0].Descriptor()
	// entregador.DefaultCreatedAt holds the default value on creation for the created_at field.
	entregador.DefaultCreatedAt = entregadorDescCreatedAt.Default.(func() time.Time)
	// entregadorDescUpdatedAt is the schema descriptor for updated_at field.
	entregadorDescUpdatedAt := entregadorMixinFields0[1].Descriptor()
	// entregador.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entregador.DefaultUpdatedAt = entregadorDescUpdatedAt.Default.(func() time.Time)
	// entregador.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entregador.UpdateDefaultUpdatedAt = entregadorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entregadorDescStatus is the schema descriptor for status field.
	entregadorDescStatus := entregadorFields[1].Descriptor()
	// entregador.DefaultStatus holds the default value on creation for the status field.
	entregador.DefaultStatus = entregadorDescStatus.Default.(string)
	// entregadorDescAvailable is the schema descriptor for available field.
	entregadorDescAvailable := entregadorFields[3].Descriptor()
	// entregador.DefaultAvailable holds the default value on creation for the available field.
	entregador.DefaultAvailable = entregadorDescAvailable.Default.(bool)
	// entregadorDescID is the schema descriptor for id field.
	entregadorDescID := entregadorFields[0].Descriptor()
	// entregador.IDValidator is a validator for the "id" field. It is called by the builders before save.
	entregador.IDValidator = entregadorDescID.Validators[0].(func(string) error)
	inventoryMixin := schema.Inventory{}.Mixin()
	inventoryMixinFields0 := inventoryMixin[0].Fields()
	_ = inventoryMixinFields0
	inventoryFields := schema.Inventory{}.Fields()
	_ = inventoryFields
	// inventoryDescCreatedAt is the schema descriptor for created_at field.
	inventoryDescCreatedAt := inventoryMixinFields0[0].Descriptor()
	// inventory.DefaultCreatedAt holds the default value on creation for the created_at field.
	inventory.DefaultCreatedAt = inventoryDescCreatedAt.Default.(func() time.Time)
	// inventoryDescUpdatedAt is the schema descriptor for updated_at field.
	inventoryDescUpdatedAt := inventoryMixinFields0[1].Descriptor()
	// inventory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inventory.DefaultUpdatedAt = inventoryDescUpdatedAt.Default.(func() time.Time)
	// inventory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inventory.UpdateDefaultUpdatedAt = inventoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// inventoryDescQuantity is the schema descriptor for quantity field.
	inventoryDescQuantity := inventoryFields[1].Descriptor()
	// inventory.DefaultQuantity holds the default value on creation for the quantity field.
	inventory.DefaultQuantity = inventoryDescQuantity.Default.(int)
	// inventoryDescReservedQuantity is the schema descriptor for reserved_quantity field.
	inventoryDescReservedQuantity := inventoryFields[2].Descriptor()
	// inventory.DefaultReservedQuantity holds the default value on creation for the reserved_quantity field.
	inventory.DefaultReservedQuantity = inventoryDescReservedQuantity.Default.(int)
	// inventoryDescID is the schema descriptor for id field.
	inventoryDescID := inventoryFields[0].Descriptor()
	// inventory.IDValidator is a validator for the "id" field. It is called by the builders before save.
	inventory.IDValidator = inventoryDescID.Validators[0].(func(string) error)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[1].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// orderDescTotalAmount is the schema descriptor for total_amount field.
	orderDescTotalAmount := orderFields[2].Descriptor()
	// order.TotalAmountValidator is a validator for the "total_amount" field. It is called by the builders before save.
	order.TotalAmountValidator = orderDescTotalAmount.Validators[0].(func(float64) error)
	// orderDescCurrency is the schema descriptor for currency field.
	orderDescCurrency := orderFields[3].Descriptor()
	// order.DefaultCurrency holds the default value on creation for the currency field.
	order.DefaultCurrency = orderDescCurrency.Default.(string)
	// orderDescDeliveryAddressJSON is the schema descriptor for delivery_address_json field.
	orderDescDeliveryAddressJSON := orderFields[4].Descriptor()
	// order.DeliveryAddressJSONValidator is a validator for the "delivery_address_json" field. It is called by the builders before save.
	order.DeliveryAddressJSONValidator = orderDescDeliveryAddressJSON.Validators[0].(func(string) error)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.IDValidator is a validator for the "id" field. It is called by the builders before save.
	order.IDValidator = orderDescID.Validators[0].(func(string) error)
	orderitemMixin := schema.OrderItem{}.Mixin()
	orderitemMixinFields0 := orderitemMixin[0].Fields()
	_ = orderitemMixinFields0
	orderitemFields := schema.OrderItem{}.Fields()
	_ = orderitemFields
	// orderitemDescCreatedAt is the schema descriptor for created_at field.
	orderitemDescCreatedAt := orderitemMixinFields0[0].Descriptor()
	// orderitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderitem.DefaultCreatedAt = orderitemDescCreatedAt.Default.(func() time.Time)
	// orderitemDescUpdatedAt is the schema descriptor for updated_at field.
	orderitemDescUpdatedAt := orderitemMixinFields0[1].Descriptor()
	// orderitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderitem.DefaultUpdatedAt = orderitemDescUpdatedAt.Default.(func() time.Time)
	// orderitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderitem.UpdateDefaultUpdatedAt = orderitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderitemDescQuantity is the schema descriptor for quantity field.
	orderitemDescQuantity := orderitemFields[1].Descriptor()
	// orderitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	orderitem.QuantityValidator = orderitemDescQuantity.Validators[0].(func(int) error)
	// orderitemDescUnitPrice is the schema descriptor for unit_price field.
	orderitemDescUnitPrice := orderitemFields[2].Descriptor()
	// orderitem.UnitPriceValidator is a validator for the "unit_price" field. It is called by the builders before save.
	orderitem.UnitPriceValidator = orderitemDescUnitPrice.Validators[0].(func(float64) error)
	// orderitemDescTotalPrice is the schema descriptor for total_price field.
	orderitemDescTotalPrice := orderitemFields[3].Descriptor()
	// orderitem.TotalPriceValidator is a validator for the "total_price" field. It is called by the builders before save.
	orderitem.TotalPriceValidator = orderitemDescTotalPrice.Validators[0].(func(float64) error)
	// orderitemDescID is the schema descriptor for id field.
	orderitemDescID := orderitemFields[0].Descriptor()
	// orderitem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	orderitem.IDValidator = orderitemDescID.Validators[0].(func(string) error)
	orderstatushistoryMixin := schema.OrderStatusHistory{}.Mixin()
	orderstatushistoryMixinFields0 := orderstatushistoryMixin[0].Fields()
	_ = orderstatushistoryMixinFields0
	orderstatushistoryFields := schema.OrderStatusHistory{}.Fields()
	_ = orderstatushistoryFields
	// orderstatushistoryDescCreatedAt is the schema descriptor for created_at field.
	orderstatushistoryDescCreatedAt := orderstatushistoryMixinFields0[0].Descriptor()
	// orderstatushistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderstatushistory.DefaultCreatedAt = orderstatushistoryDescCreatedAt.Default.(func() time.Time)
	// orderstatushistoryDescUpdatedAt is the schema descriptor for updated_at field.
	orderstatushistoryDescUpdatedAt := orderstatushistoryMixinFields0[1].Descriptor()
	// orderstatushistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderstatushistory.DefaultUpdatedAt = orderstatushistoryDescUpdatedAt.Default.(func() time.Time)
	// orderstatushistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderstatushistory.UpdateDefaultUpdatedAt = orderstatushistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderstatushistoryDescStatus is the schema descriptor for status field.
	orderstatushistoryDescStatus := orderstatushistoryFields[1].Descriptor()
	// orderstatushistory.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	orderstatushistory.StatusValidator = orderstatushistoryDescStatus.Validators[0].(func(string) error)
	// orderstatushistoryDescChangedAt is the schema descriptor for changed_at field.
	orderstatushistoryDescChangedAt := orderstatushistoryFields[3].Descriptor()
	// orderstatushistory.DefaultChangedAt holds the default value on creation for the changed_at field.
	orderstatushistory.DefaultChangedAt = orderstatushistoryDescChangedAt.Default.(func() time.Time)
	// orderstatushistoryDescID is the schema descriptor for id field.
	orderstatushistoryDescID := orderstatushistoryFields[0].Descriptor()
	// orderstatushistory.IDValidator is a validator for the "id" field. It is called by the builders before save.
	orderstatushistory.IDValidator = orderstatushistoryDescID.Validators[0].(func(string) error)
	outboxeventMixin := schema.OutboxEvent{}.Mixin()
	outboxeventMixinFields0 := outboxeventMixin[0].Fields()
	_ = outboxeventMixinFields0
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventMixinFields0[0].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescUpdatedAt is the schema descriptor for updated_at field.
	outboxeventDescUpdatedAt := outboxeventMixinFields0[1].Descriptor()
	// outboxevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	outboxevent.DefaultUpdatedAt = outboxeventDescUpdatedAt.Default.(func() time.Time)
	// outboxevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	outboxevent.UpdateDefaultUpdatedAt = outboxeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[1].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescAggregateID is the schema descriptor for aggregate_id field.
	outboxeventDescAggregateID := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	outboxevent.AggregateIDValidator = outboxeventDescAggregateID.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[3].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescEventVersion is the schema descriptor for event_version field.
	outboxeventDescEventVersion := outboxeventFields[4].Descriptor()
	// outboxevent.DefaultEventVersion holds the default value on creation for the event_version field.
	outboxevent.DefaultEventVersion = outboxeventDescEventVersion.Default.(string)
	// outboxeventDescPayloadJSON is the schema descriptor for payload_json field.
	outboxeventDescPayloadJSON := outboxeventFields[5].Descriptor()
	// outboxevent.PayloadJSONValidator is a validator for the "payload_json" field. It is called by the builders before save.
	outboxevent.PayloadJSONValidator = outboxeventDescPayloadJSON.Validators[0].(func(string) error)
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(string)
	// outboxeventDescRetryCount is the schema descriptor for retry_count field.
	outboxeventDescRetryCount := outboxeventFields[8].Descriptor()
	// outboxevent.DefaultRetryCount holds the default value on creation for the retry_count field.
	outboxevent.DefaultRetryCount = outboxeventDescRetryCount.Default.(int)
	// outboxeventDescNextAttemptAt is the schema descriptor for next_attempt_at field.
	outboxeventDescNextAttemptAt := outboxeventFields[9].Descriptor()
	// outboxevent.DefaultNextAttemptAt holds the default value on creation for the next_attempt_at field.
	outboxevent.DefaultNextAttemptAt = outboxeventDescNextAttemptAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	outboxevent.IDValidator = outboxeventDescID.Validators[0].(func(string) error)
	paymentMixin := schema.Payment{}.Mixin()
	paymentMixinFields0 := paymentMixin[0].Fields()
	_ = paymentMixinFields0
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentMixinFields0[0].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	// paymentDescUpdatedAt is the schema descriptor for updated_at field.
	paymentDescUpdatedAt := paymentMixinFields0[1].Descriptor()
	// payment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	payment.DefaultUpdatedAt = paymentDescUpdatedAt.Default.(func() time.Time)
	// payment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	payment.UpdateDefaultUpdatedAt = paymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentDescProvider is the schema descriptor for provider field.
	paymentDescProvider := paymentFields[1].Descriptor()
	// payment.DefaultProvider holds the default value on creation for the provider field.
	payment.DefaultProvider = paymentDescProvider.Default.(string)
	// paymentDescStatus is the schema descriptor for status field.
	paymentDescStatus := paymentFields[2].Descriptor()
	// payment.DefaultStatus holds the default value on creation for the status field.
	payment.DefaultStatus = paymentDescStatus.Default.(string)
	// paymentDescAmount is the schema descriptor for amount field.
	paymentDescAmount := paymentFields[3].Descriptor()
	// payment.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	payment.AmountValidator = paymentDescAmount.Validators[0].(func(float64) error)
	// paymentDescCurrency is the schema descriptor for currency field.
	paymentDescCurrency := paymentFields[4].Descriptor()
	// payment.DefaultCurrency holds the default value on creation for the currency field.
	payment.DefaultCurrency = paymentDescCurrency.Default.(string)
	// paymentDescID is the schema descriptor for id field.
	paymentDescID := paymentFields[0].Descriptor()
	// payment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	payment.IDValidator = paymentDescID.Validators[0].(func(string) error)
	productMixin := schema.Product{}.Mixin()
	productMixinFields0 := productMixin[0].Fields()
	_ = productMixinFields0
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productMixinFields0[0].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productMixinFields0[1].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[1].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescPrice is the schema descriptor for price field.
	productDescPrice := productFields[3].Descriptor()
	// product.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	product.PriceValidator = productDescPrice.Validators[0].(func(float64) error)
	// productDescStatus is the schema descriptor for status field.
	productDescStatus := productFields[4].Descriptor()
	// product.DefaultStatus holds the default value on creation for the status field.
	product.DefaultStatus = productDescStatus.Default.(string)
	// productDescSlug is the schema descriptor for slug field.
	productDescSlug := productFields[5].Descriptor()
	// product.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	product.SlugValidator = productDescSlug.Validators[0].(func(string) error)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.IDValidator is a validator for the "id" field. It is called by the builders before save.
	product.IDValidator = productDescID.Validators[0].(func(string) error)
	productimageMixin := schema.ProductImage{}.Mixin()
	productimageMixinFields0 := productimageMixin[0].Fields()
	_ = productimageMixinFields0
	productimageFields := schema.ProductImage{}.Fields()
	_ = productimageFields
	// productimageDescCreatedAt is the schema descriptor for created_at field.
	productimageDescCreatedAt := productimageMixinFields0[0].Descriptor()
	// productimage.DefaultCreatedAt holds the default value on creation for the created_at field.
	productimage.DefaultCreatedAt = productimageDescCreatedAt.Default.(func() time.Time)
	// productimageDescUpdatedAt is the schema descriptor for updated_at field.
	productimageDescUpdatedAt := productimageMixinFields0[1].Descriptor()
	// productimage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	productimage.DefaultUpdatedAt = productimageDescUpdatedAt.Default.(func() time.Time)
	// productimage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productimage.UpdateDefaultUpdatedAt = productimageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productimageDescPosition is the schema descriptor for position field.
	productimageDescPosition := productimageFields[1].Descriptor()
	// productimage.DefaultPosition holds the default value on creation for the position field.
	productimage.DefaultPosition = productimageDescPosition.Default.(int)
	// productimageDescID is the schema descriptor for id field.
	productimageDescID := productimageFields[0].Descriptor()
	// productimage.IDValidator is a validator for the "id" field. It is called by the builders before save.
	productimage.IDValidator = productimageDescID.Validators[0].(func(string) error)
	sellerMixin := schema.Seller{}.Mixin()
	sellerMixinFields0 := sellerMixin[0].Fields()
	_ = sellerMixinFields0
	sellerFields := schema.Seller{}.Fields()
	_ = sellerFields
	// sellerDescCreatedAt is the schema descriptor for created_at field.
	sellerDescCreatedAt := sellerMixinFields0[0].Descriptor()
	// seller.DefaultCreatedAt holds the default value on creation for the created_at field.
	seller.DefaultCreatedAt = sellerDescCreatedAt.Default.(func() time.Time)
	// sellerDescUpdatedAt is the schema descriptor for updated_at field.
	sellerDescUpdatedAt := sellerMixinFields0[1].Descriptor()
	// seller.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	seller.DefaultUpdatedAt = sellerDescUpdatedAt.Default.(func() time.Time)
	// seller.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	seller.UpdateDefaultUpdatedAt = sellerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sellerDescName is the schema descriptor for name field.
	sellerDescName := sellerFields[1].Descriptor()
	// seller.NameValidator is a validator for the "name" field. It is called by the builders before save.
	seller.NameValidator = sellerDescName.Validators[0].(func(string) error)
	// sellerDescDocument is the schema descriptor for document field.
	sellerDescDocument := sellerFields[2].Descriptor()
	// seller.DocumentValidator is a validator for the "document" field. It is called by the builders before save.
	seller.DocumentValidator = sellerDescDocument.Validators[0].(func(string) error)
	// sellerDescStatus is the schema descriptor for status field.
	sellerDescStatus := sellerFields[3].Descriptor()
	// seller.DefaultStatus holds the default value on creation for the status field.
	seller.DefaultStatus = sellerDescStatus.Default.(string)
	// sellerDescID is the schema descriptor for id field.
	sellerDescID := sellerFields[0].Descriptor()
	// seller.IDValidator is a validator for the "id" field. It is called by the builders before save.
	seller.IDValidator = sellerDescID.Validators[0].(func(string) error)
	selleruserMixin := schema.SellerUser{}.Mixin()
	selleruserMixinFields0 := selleruserMixin[0].Fields()
	_ = selleruserMixinFields0
	selleruserFields := schema.SellerUser{}.Fields()
	_ = selleruserFields
	// selleruserDescCreatedAt is the schema descriptor for created_at field.
	selleruserDescCreatedAt := selleruserMixinFields0[0].Descriptor()
	// selleruser.DefaultCreatedAt holds the default value on creation for the created_at field.
	selleruser.DefaultCreatedAt = selleruserDescCreatedAt.Default.(func() time.Time)
	// selleruserDescUpdatedAt is the schema descriptor for updated_at field.
	selleruserDescUpdatedAt := selleruserMixinFields0[1].Descriptor()
	// selleruser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	selleruser.DefaultUpdatedAt = selleruserDescUpdatedAt.Default.(func() time.Time)
	// selleruser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	selleruser.UpdateDefaultUpdatedAt = selleruserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// selleruserDescRole is the schema descriptor for role field.
	selleruserDescRole := selleruserFields[1].Descriptor()
	// selleruser.DefaultRole holds the default value on creation for the role field.
	selleruser.DefaultRole = selleruserDescRole.Default.(string)
	// selleruserDescID is the schema descriptor for id field.
	selleruserDescID := selleruserFields[0].Descriptor()
	// selleruser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	selleruser.IDValidator = selleruserDescID.Validators[0].(func(string) error)
	uploadMixin := schema.Upload{}.Mixin()
	uploadMixinFields0 := uploadMixin[0].Fields()
	_ = uploadMixinFields0
	uploadFields := schema.Upload{}.Fields()
	_ = uploadFields
	// uploadDescCreatedAt is the schema descriptor for created_at field.
	uploadDescCreatedAt := uploadMixinFields0[0].Descriptor()
	// upload.DefaultCreatedAt holds the default value on creation for the created_at field.
	upload.DefaultCreatedAt = uploadDescCreatedAt.Default.(func() time.Time)
	// uploadDescUpdatedAt is the schema descriptor for updated_at field.
	uploadDescUpdatedAt := uploadMixinFields0[1].Descriptor()
	// upload.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	upload.DefaultUpdatedAt = uploadDescUpdatedAt.Default.(func() time.Time)
	// upload.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	upload.UpdateDefaultUpdatedAt = uploadDescUpdatedAt.UpdateDefault.(func() time.Time)
	// uploadDescFilename is the schema descriptor for filename field.
	uploadDescFilename := uploadFields[1].Descriptor()
	// upload.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	upload.FilenameValidator = uploadDescFilename.Validators[0].(func(string) error)
	// uploadDescStatus is the schema descriptor for status field.
	uploadDescStatus := uploadFields[3].Descriptor()
	// upload.DefaultStatus holds the default value on creation for the status field.
	upload.DefaultStatus = uploadDescStatus.Default.(string)
	// uploadDescID is the schema descriptor for id field.
	uploadDescID := uploadFields[0].Descriptor()
	// upload.IDValidator is a validator for the "id" field. It is called by the builders before save.
	upload.IDValidator = uploadDescID.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
