// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/sellerdeliveryarea"
)

// SellerDeliveryAreaCreate is the builder for creating a SellerDeliveryArea entity.
type SellerDeliveryAreaCreate struct {
	config
	mutation *SellerDeliveryAreaMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SellerDeliveryAreaCreate) SetCreatedAt(v time.Time) *SellerDeliveryAreaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SellerDeliveryAreaCreate) SetNillableCreatedAt(v *time.Time) *SellerDeliveryAreaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SellerDeliveryAreaCreate) SetUpdatedAt(v time.Time) *SellerDeliveryAreaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SellerDeliveryAreaCreate) SetNillableUpdatedAt(v *time.Time) *SellerDeliveryAreaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *SellerDeliveryAreaCreate) SetLabel(v string) *SellerDeliveryAreaCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetFee sets the "fee" field.
func (_c *SellerDeliveryAreaCreate) SetFee(v float64) *SellerDeliveryAreaCreate {
	_c.mutation.SetFee(v)
	return _c
}

// SetNillableFee sets the "fee" field if the given value is not nil.
func (_c *SellerDeliveryAreaCreate) SetNillableFee(v *float64) *SellerDeliveryAreaCreate {
	if v != nil {
		_c.SetFee(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SellerDeliveryAreaCreate) SetID(v string) *SellerDeliveryAreaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_c *SellerDeliveryAreaCreate) SetSellerID(id string) *SellerDeliveryAreaCreate {
	_c.mutation.SetSellerID(id)
	return _c
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_c *SellerDeliveryAreaCreate) SetSeller(v *Seller) *SellerDeliveryAreaCreate {
	return _c.SetSellerID(v.ID)
}

// Mutation returns the SellerDeliveryAreaMutation object of the builder.
func (_c *SellerDeliveryAreaCreate) Mutation() *SellerDeliveryAreaMutation {
	return _c.mutation
}

// Save creates the SellerDeliveryArea in the database.
func (_c *SellerDeliveryAreaCreate) Save(ctx context.Context) (*SellerDeliveryArea, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SellerDeliveryAreaCreate) SaveX(ctx context.Context) *SellerDeliveryArea {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SellerDeliveryAreaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SellerDeliveryAreaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SellerDeliveryAreaCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sellerdeliveryarea.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sellerdeliveryarea.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Fee(); !ok {
		v := sellerdeliveryarea.DefaultFee
		_c.mutation.SetFee(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SellerDeliveryAreaCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SellerDeliveryArea.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SellerDeliveryArea.updated_at"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "SellerDeliveryArea.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := sellerdeliveryarea.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "SellerDeliveryArea.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fee(); !ok {
		return &ValidationError{Name: "fee", err: errors.New(`ent: missing required field "SellerDeliveryArea.fee"`)}
	}
	if v, ok := _c.mutation.Fee(); ok {
		if err := sellerdeliveryarea.FeeValidator(v); err != nil {
			return &ValidationError{Name: "fee", err: fmt.Errorf(`ent: validator failed for field "SellerDeliveryArea.fee": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sellerdeliveryarea.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SellerDeliveryArea.id": %w`, err)}
		}
	}
	if len(_c.mutation.SellerIDs()) == 0 {
		return &ValidationError{Name: "seller", err: errors.New(`ent: missing required edge "SellerDeliveryArea.seller"`)}
	}
	return nil
}

func (_c *SellerDeliveryAreaCreate) sqlSave(ctx context.Context) (*SellerDeliveryArea, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SellerDeliveryArea.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SellerDeliveryAreaCreate) createSpec() (*SellerDeliveryArea, *sqlgraph.CreateSpec) {
	var (
		_node = &SellerDeliveryArea{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sellerdeliveryarea.Table, sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sellerdeliveryarea.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sellerdeliveryarea.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(sellerdeliveryarea.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Fee(); ok {
		_spec.SetField(sellerdeliveryarea.FieldFee, field.TypeFloat64, value)
		_node.Fee = value
	}
	if nodes := _c.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerdeliveryarea.SellerTable,
			Columns: []string{sellerdeliveryarea.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.seller_delivery_areas = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SellerDeliveryAreaCreateBulk is the builder for creating many SellerDeliveryArea entities in bulk.
type SellerDeliveryAreaCreateBulk struct {
	config
	err      error
	builders []*SellerDeliveryAreaCreate
}

// Save creates the SellerDeliveryArea entities in the database.
func (_c *SellerDeliveryAreaCreateBulk) Save(ctx context.Context) ([]*SellerDeliveryArea, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SellerDeliveryArea, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SellerDeliveryAreaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SellerDeliveryAreaCreateBulk) SaveX(ctx context.Context) []*SellerDeliveryArea {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SellerDeliveryAreaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SellerDeliveryAreaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
