// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/inventory"
	"github.com/entregamais/platform/backend/ent/order"
	"github.com/entregamais/platform/backend/ent/predicate"
	"github.com/entregamais/platform/backend/ent/product"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/sellerdeliveryarea"
	"github.com/entregamais/platform/backend/ent/sellerreview"
	"github.com/entregamais/platform/backend/ent/selleruser"
)

// SellerUpdate is the builder for updating Seller entities.
type SellerUpdate struct {
	config
	hooks    []Hook
	mutation *SellerMutation
}

// Where appends a list predicates to the SellerUpdate builder.
func (_u *SellerUpdate) Where(ps ...predicate.Seller) *SellerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerUpdate) SetUpdatedAt(v time.Time) *SellerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SellerUpdate) SetName(v string) *SellerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SellerUpdate) SetNillableName(v *string) *SellerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *SellerUpdate) SetDocument(v string) *SellerUpdate {
	_u.mutation.SetDocument(v)
	return _u
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (_u *SellerUpdate) SetNillableDocument(v *string) *SellerUpdate {
	if v != nil {
		_u.SetDocument(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SellerUpdate) SetStatus(v string) *SellerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SellerUpdate) SetNillableStatus(v *string) *SellerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SellerUpdate) SetDeletedAt(v time.Time) *SellerUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SellerUpdate) SetNillableDeletedAt(v *time.Time) *SellerUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SellerUpdate) ClearDeletedAt() *SellerUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddUserIDs adds the "users" edge to the SellerUser entity by IDs.
func (_u *SellerUpdate) AddUserIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the SellerUser entity.
func (_u *SellerUpdate) AddUsers(v ...*SellerUser) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *SellerUpdate) AddProductIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *SellerUpdate) AddProducts(v ...*Product) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// AddInventoryIDs adds the "inventory" edge to the Inventory entity by IDs.
func (_u *SellerUpdate) AddInventoryIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventory adds the "inventory" edges to the Inventory entity.
func (_u *SellerUpdate) AddInventory(v ...*Inventory) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *SellerUpdate) AddOrderIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *SellerUpdate) AddOrders(v ...*Order) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// AddDeliveryAreaIDs adds the "delivery_areas" edge to the SellerDeliveryArea entity by IDs.
func (_u *SellerUpdate) AddDeliveryAreaIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddDeliveryAreaIDs(ids...)
	return _u
}

// AddDeliveryAreas adds the "delivery_areas" edges to the SellerDeliveryArea entity.
func (_u *SellerUpdate) AddDeliveryAreas(v ...*SellerDeliveryArea) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeliveryAreaIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the SellerReview entity by IDs.
func (_u *SellerUpdate) AddReviewIDs(ids ...string) *SellerUpdate {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the SellerReview entity.
func (_u *SellerUpdate) AddReviews(v ...*SellerReview) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the SellerMutation object of the builder.
func (_u *SellerUpdate) Mutation() *SellerMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the SellerUser entity.
func (_u *SellerUpdate) ClearUsers() *SellerUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to SellerUser entities by IDs.
func (_u *SellerUpdate) RemoveUserIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to SellerUser entities.
func (_u *SellerUpdate) RemoveUsers(v ...*SellerUser) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *SellerUpdate) ClearProducts() *SellerUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *SellerUpdate) RemoveProductIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *SellerUpdate) RemoveProducts(v ...*Product) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// ClearInventory clears all "inventory" edges to the Inventory entity.
func (_u *SellerUpdate) ClearInventory() *SellerUpdate {
	_u.mutation.ClearInventory()
	return _u
}

// RemoveInventoryIDs removes the "inventory" edge to Inventory entities by IDs.
func (_u *SellerUpdate) RemoveInventoryIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventory removes "inventory" edges to Inventory entities.
func (_u *SellerUpdate) RemoveInventory(v ...*Inventory) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *SellerUpdate) ClearOrders() *SellerUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *SellerUpdate) RemoveOrderIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *SellerUpdate) RemoveOrders(v ...*Order) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// ClearDeliveryAreas clears all "delivery_areas" edges to the SellerDeliveryArea entity.
func (_u *SellerUpdate) ClearDeliveryAreas() *SellerUpdate {
	_u.mutation.ClearDeliveryAreas()
	return _u
}

// RemoveDeliveryAreaIDs removes the "delivery_areas" edge to SellerDeliveryArea entities by IDs.
func (_u *SellerUpdate) RemoveDeliveryAreaIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveDeliveryAreaIDs(ids...)
	return _u
}

// RemoveDeliveryAreas removes "delivery_areas" edges to SellerDeliveryArea entities.
func (_u *SellerUpdate) RemoveDeliveryAreas(v ...*SellerDeliveryArea) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeliveryAreaIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the SellerReview entity.
func (_u *SellerUpdate) ClearReviews() *SellerUpdate {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to SellerReview entities by IDs.
func (_u *SellerUpdate) RemoveReviewIDs(ids ...string) *SellerUpdate {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to SellerReview entities.
func (_u *SellerUpdate) RemoveReviews(v ...*SellerReview) *SellerUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SellerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SellerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := seller.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := seller.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Seller.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Document(); ok {
		if err := seller.DocumentValidator(v); err != nil {
			return &ValidationError{Name: "document", err: fmt.Errorf(`ent: validator failed for field "Seller.document": %w`, err)}
		}
	}
	return nil
}

func (_u *SellerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(seller.Table, seller.Columns, sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(seller.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(seller.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(seller.FieldDocument, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(seller.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(seller.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(seller.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryIDs(); len(nodes) > 0 && !_u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeliveryAreasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeliveryAreasIDs(); len(nodes) > 0 && !_u.mutation.DeliveryAreasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeliveryAreasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{seller.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SellerUpdateOne is the builder for updating a single Seller entity.
type SellerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SellerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerUpdateOne) SetUpdatedAt(v time.Time) *SellerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SellerUpdateOne) SetName(v string) *SellerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SellerUpdateOne) SetNillableName(v *string) *SellerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *SellerUpdateOne) SetDocument(v string) *SellerUpdateOne {
	_u.mutation.SetDocument(v)
	return _u
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (_u *SellerUpdateOne) SetNillableDocument(v *string) *SellerUpdateOne {
	if v != nil {
		_u.SetDocument(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SellerUpdateOne) SetStatus(v string) *SellerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SellerUpdateOne) SetNillableStatus(v *string) *SellerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SellerUpdateOne) SetDeletedAt(v time.Time) *SellerUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SellerUpdateOne) SetNillableDeletedAt(v *time.Time) *SellerUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SellerUpdateOne) ClearDeletedAt() *SellerUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddUserIDs adds the "users" edge to the SellerUser entity by IDs.
func (_u *SellerUpdateOne) AddUserIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the SellerUser entity.
func (_u *SellerUpdateOne) AddUsers(v ...*SellerUser) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *SellerUpdateOne) AddProductIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *SellerUpdateOne) AddProducts(v ...*Product) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// AddInventoryIDs adds the "inventory" edge to the Inventory entity by IDs.
func (_u *SellerUpdateOne) AddInventoryIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventory adds the "inventory" edges to the Inventory entity.
func (_u *SellerUpdateOne) AddInventory(v ...*Inventory) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *SellerUpdateOne) AddOrderIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *SellerUpdateOne) AddOrders(v ...*Order) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// AddDeliveryAreaIDs adds the "delivery_areas" edge to the SellerDeliveryArea entity by IDs.
func (_u *SellerUpdateOne) AddDeliveryAreaIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddDeliveryAreaIDs(ids...)
	return _u
}

// AddDeliveryAreas adds the "delivery_areas" edges to the SellerDeliveryArea entity.
func (_u *SellerUpdateOne) AddDeliveryAreas(v ...*SellerDeliveryArea) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeliveryAreaIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the SellerReview entity by IDs.
func (_u *SellerUpdateOne) AddReviewIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.AddReviewIDs(ids...)
	return _u
}

// AddReviews adds the "reviews" edges to the SellerReview entity.
func (_u *SellerUpdateOne) AddReviews(v ...*SellerReview) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewIDs(ids...)
}

// Mutation returns the SellerMutation object of the builder.
func (_u *SellerUpdateOne) Mutation() *SellerMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the SellerUser entity.
func (_u *SellerUpdateOne) ClearUsers() *SellerUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to SellerUser entities by IDs.
func (_u *SellerUpdateOne) RemoveUserIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to SellerUser entities.
func (_u *SellerUpdateOne) RemoveUsers(v ...*SellerUser) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *SellerUpdateOne) ClearProducts() *SellerUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *SellerUpdateOne) RemoveProductIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *SellerUpdateOne) RemoveProducts(v ...*Product) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// ClearInventory clears all "inventory" edges to the Inventory entity.
func (_u *SellerUpdateOne) ClearInventory() *SellerUpdateOne {
	_u.mutation.ClearInventory()
	return _u
}

// RemoveInventoryIDs removes the "inventory" edge to Inventory entities by IDs.
func (_u *SellerUpdateOne) RemoveInventoryIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventory removes "inventory" edges to Inventory entities.
func (_u *SellerUpdateOne) RemoveInventory(v ...*Inventory) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *SellerUpdateOne) ClearOrders() *SellerUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *SellerUpdateOne) RemoveOrderIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *SellerUpdateOne) RemoveOrders(v ...*Order) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// ClearDeliveryAreas clears all "delivery_areas" edges to the SellerDeliveryArea entity.
func (_u *SellerUpdateOne) ClearDeliveryAreas() *SellerUpdateOne {
	_u.mutation.ClearDeliveryAreas()
	return _u
}

// RemoveDeliveryAreaIDs removes the "delivery_areas" edge to SellerDeliveryArea entities by IDs.
func (_u *SellerUpdateOne) RemoveDeliveryAreaIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveDeliveryAreaIDs(ids...)
	return _u
}

// RemoveDeliveryAreas removes "delivery_areas" edges to SellerDeliveryArea entities.
func (_u *SellerUpdateOne) RemoveDeliveryAreas(v ...*SellerDeliveryArea) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeliveryAreaIDs(ids...)
}

// ClearReviews clears all "reviews" edges to the SellerReview entity.
func (_u *SellerUpdateOne) ClearReviews() *SellerUpdateOne {
	_u.mutation.ClearReviews()
	return _u
}

// RemoveReviewIDs removes the "reviews" edge to SellerReview entities by IDs.
func (_u *SellerUpdateOne) RemoveReviewIDs(ids ...string) *SellerUpdateOne {
	_u.mutation.RemoveReviewIDs(ids...)
	return _u
}

// RemoveReviews removes "reviews" edges to SellerReview entities.
func (_u *SellerUpdateOne) RemoveReviews(v ...*SellerReview) *SellerUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewIDs(ids...)
}

// Where appends a list predicates to the SellerUpdate builder.
func (_u *SellerUpdateOne) Where(ps ...predicate.Seller) *SellerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SellerUpdateOne) Select(field string, fields ...string) *SellerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Seller entity.
func (_u *SellerUpdateOne) Save(ctx context.Context) (*Seller, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerUpdateOne) SaveX(ctx context.Context) *Seller {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SellerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := seller.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := seller.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Seller.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Document(); ok {
		if err := seller.DocumentValidator(v); err != nil {
			return &ValidationError{Name: "document", err: fmt.Errorf(`ent: validator failed for field "Seller.document": %w`, err)}
		}
	}
	return nil
}

func (_u *SellerUpdateOne) sqlSave(ctx context.Context) (_node *Seller, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(seller.Table, seller.Columns, sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Seller.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, seller.FieldID)
		for _, f := range fields {
			if !seller.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != seller.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(seller.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(seller.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(seller.FieldDocument, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(seller.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(seller.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(seller.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.UsersTable,
			Columns: []string{seller.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ProductsTable,
			Columns: []string{seller.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryIDs(); len(nodes) > 0 && !_u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.InventoryTable,
			Columns: []string{seller.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.OrdersTable,
			Columns: []string{seller.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeliveryAreasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeliveryAreasIDs(); len(nodes) > 0 && !_u.mutation.DeliveryAreasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeliveryAreasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.DeliveryAreasTable,
			Columns: []string{seller.DeliveryAreasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerdeliveryarea.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewsIDs(); len(nodes) > 0 && !_u.mutation.ReviewsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seller.ReviewsTable,
			Columns: []string{seller.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Seller{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{seller.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
