// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/predicate"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/selleruser"
	"github.com/entregamais/platform/backend/ent/user"
)

// SellerUserUpdate is the builder for updating SellerUser entities.
type SellerUserUpdate struct {
	config
	hooks    []Hook
	mutation *SellerUserMutation
}

// Where appends a list predicates to the SellerUserUpdate builder.
func (_u *SellerUserUpdate) Where(ps ...predicate.SellerUser) *SellerUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerUserUpdate) SetUpdatedAt(v time.Time) *SellerUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SellerUserUpdate) SetRole(v string) *SellerUserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SellerUserUpdate) SetNillableRole(v *string) *SellerUserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *SellerUserUpdate) SetSellerID(id string) *SellerUserUpdate {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *SellerUserUpdate) SetSeller(v *Seller) *SellerUserUpdate {
	return _u.SetSellerID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SellerUserUpdate) SetUserID(id string) *SellerUserUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SellerUserUpdate) SetUser(v *User) *SellerUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SellerUserMutation object of the builder.
func (_u *SellerUserUpdate) Mutation() *SellerUserMutation {
	return _u.mutation
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *SellerUserUpdate) ClearSeller() *SellerUserUpdate {
	_u.mutation.ClearSeller()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SellerUserUpdate) ClearUser() *SellerUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SellerUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SellerUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := selleruser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerUserUpdate) check() error {
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerUser.seller"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerUser.user"`)
	}
	return nil
}

func (_u *SellerUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(selleruser.Table, selleruser.Columns, sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(selleruser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(selleruser.FieldRole, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.SellerTable,
			Columns: []string{selleruser.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.SellerTable,
			Columns: []string{selleruser.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.UserTable,
			Columns: []string{selleruser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.UserTable,
			Columns: []string{selleruser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{selleruser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SellerUserUpdateOne is the builder for updating a single SellerUser entity.
type SellerUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SellerUserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerUserUpdateOne) SetUpdatedAt(v time.Time) *SellerUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *SellerUserUpdateOne) SetRole(v string) *SellerUserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SellerUserUpdateOne) SetNillableRole(v *string) *SellerUserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *SellerUserUpdateOne) SetSellerID(id string) *SellerUserUpdateOne {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *SellerUserUpdateOne) SetSeller(v *Seller) *SellerUserUpdateOne {
	return _u.SetSellerID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SellerUserUpdateOne) SetUserID(id string) *SellerUserUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SellerUserUpdateOne) SetUser(v *User) *SellerUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SellerUserMutation object of the builder.
func (_u *SellerUserUpdateOne) Mutation() *SellerUserMutation {
	return _u.mutation
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *SellerUserUpdateOne) ClearSeller() *SellerUserUpdateOne {
	_u.mutation.ClearSeller()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SellerUserUpdateOne) ClearUser() *SellerUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SellerUserUpdate builder.
func (_u *SellerUserUpdateOne) Where(ps ...predicate.SellerUser) *SellerUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SellerUserUpdateOne) Select(field string, fields ...string) *SellerUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SellerUser entity.
func (_u *SellerUserUpdateOne) Save(ctx context.Context) (*SellerUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerUserUpdateOne) SaveX(ctx context.Context) *SellerUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SellerUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := selleruser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerUserUpdateOne) check() error {
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerUser.seller"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerUser.user"`)
	}
	return nil
}

func (_u *SellerUserUpdateOne) sqlSave(ctx context.Context) (_node *SellerUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(selleruser.Table, selleruser.Columns, sqlgraph.NewFieldSpec(selleruser.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SellerUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, selleruser.FieldID)
		for _, f := range fields {
			if !selleruser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != selleruser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(selleruser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(selleruser.FieldRole, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.SellerTable,
			Columns: []string{selleruser.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.SellerTable,
			Columns: []string{selleruser.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.UserTable,
			Columns: []string{selleruser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   selleruser.UserTable,
			Columns: []string{selleruser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SellerUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{selleruser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
