// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/predicate"
	"github.com/entregamais/platform/backend/ent/seller"
	"github.com/entregamais/platform/backend/ent/sellerreview"
	"github.com/entregamais/platform/backend/ent/user"
)

// SellerReviewUpdate is the builder for updating SellerReview entities.
type SellerReviewUpdate struct {
	config
	hooks    []Hook
	mutation *SellerReviewMutation
}

// Where appends a list predicates to the SellerReviewUpdate builder.
func (_u *SellerReviewUpdate) Where(ps ...predicate.SellerReview) *SellerReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerReviewUpdate) SetUpdatedAt(v time.Time) *SellerReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *SellerReviewUpdate) SetScore(v int) *SellerReviewUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SellerReviewUpdate) SetNillableScore(v *int) *SellerReviewUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SellerReviewUpdate) AddScore(v int) *SellerReviewUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *SellerReviewUpdate) SetComment(v string) *SellerReviewUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SellerReviewUpdate) SetNillableComment(v *string) *SellerReviewUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *SellerReviewUpdate) ClearComment() *SellerReviewUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *SellerReviewUpdate) SetSellerID(id string) *SellerReviewUpdate {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *SellerReviewUpdate) SetSeller(v *Seller) *SellerReviewUpdate {
	return _u.SetSellerID(v.ID)
}

// SetCustomerID sets the "customer" edge to the User entity by ID.
func (_u *SellerReviewUpdate) SetCustomerID(id string) *SellerReviewUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the User entity.
func (_u *SellerReviewUpdate) SetCustomer(v *User) *SellerReviewUpdate {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the SellerReviewMutation object of the builder.
func (_u *SellerReviewUpdate) Mutation() *SellerReviewMutation {
	return _u.mutation
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *SellerReviewUpdate) ClearSeller() *SellerReviewUpdate {
	_u.mutation.ClearSeller()
	return _u
}

// ClearCustomer clears the "customer" edge to the User entity.
func (_u *SellerReviewUpdate) ClearCustomer() *SellerReviewUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SellerReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SellerReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sellerreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerReviewUpdate) check() error {
	if v, ok := _u.mutation.Score(); ok {
		if err := sellerreview.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "SellerReview.score": %w`, err)}
		}
	}
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerReview.seller"`)
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerReview.customer"`)
	}
	return nil
}

func (_u *SellerReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sellerreview.Table, sellerreview.Columns, sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sellerreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(sellerreview.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(sellerreview.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(sellerreview.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(sellerreview.FieldComment, field.TypeString)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.SellerTable,
			Columns: []string{sellerreview.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.SellerTable,
			Columns: []string{sellerreview.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.CustomerTable,
			Columns: []string{sellerreview.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.CustomerTable,
			Columns: []string{sellerreview.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sellerreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SellerReviewUpdateOne is the builder for updating a single SellerReview entity.
type SellerReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SellerReviewMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SellerReviewUpdateOne) SetUpdatedAt(v time.Time) *SellerReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *SellerReviewUpdateOne) SetScore(v int) *SellerReviewUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *SellerReviewUpdateOne) SetNillableScore(v *int) *SellerReviewUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *SellerReviewUpdateOne) AddScore(v int) *SellerReviewUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *SellerReviewUpdateOne) SetComment(v string) *SellerReviewUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SellerReviewUpdateOne) SetNillableComment(v *string) *SellerReviewUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *SellerReviewUpdateOne) ClearComment() *SellerReviewUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetSellerID sets the "seller" edge to the Seller entity by ID.
func (_u *SellerReviewUpdateOne) SetSellerID(id string) *SellerReviewUpdateOne {
	_u.mutation.SetSellerID(id)
	return _u
}

// SetSeller sets the "seller" edge to the Seller entity.
func (_u *SellerReviewUpdateOne) SetSeller(v *Seller) *SellerReviewUpdateOne {
	return _u.SetSellerID(v.ID)
}

// SetCustomerID sets the "customer" edge to the User entity by ID.
func (_u *SellerReviewUpdateOne) SetCustomerID(id string) *SellerReviewUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the User entity.
func (_u *SellerReviewUpdateOne) SetCustomer(v *User) *SellerReviewUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the SellerReviewMutation object of the builder.
func (_u *SellerReviewUpdateOne) Mutation() *SellerReviewMutation {
	return _u.mutation
}

// ClearSeller clears the "seller" edge to the Seller entity.
func (_u *SellerReviewUpdateOne) ClearSeller() *SellerReviewUpdateOne {
	_u.mutation.ClearSeller()
	return _u
}

// ClearCustomer clears the "customer" edge to the User entity.
func (_u *SellerReviewUpdateOne) ClearCustomer() *SellerReviewUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// Where appends a list predicates to the SellerReviewUpdate builder.
func (_u *SellerReviewUpdateOne) Where(ps ...predicate.SellerReview) *SellerReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SellerReviewUpdateOne) Select(field string, fields ...string) *SellerReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SellerReview entity.
func (_u *SellerReviewUpdateOne) Save(ctx context.Context) (*SellerReview, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SellerReviewUpdateOne) SaveX(ctx context.Context) *SellerReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SellerReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SellerReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SellerReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sellerreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SellerReviewUpdateOne) check() error {
	if v, ok := _u.mutation.Score(); ok {
		if err := sellerreview.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "SellerReview.score": %w`, err)}
		}
	}
	if _u.mutation.SellerCleared() && len(_u.mutation.SellerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerReview.seller"`)
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SellerReview.customer"`)
	}
	return nil
}

func (_u *SellerReviewUpdateOne) sqlSave(ctx context.Context) (_node *SellerReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sellerreview.Table, sellerreview.Columns, sqlgraph.NewFieldSpec(sellerreview.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SellerReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sellerreview.FieldID)
		for _, f := range fields {
			if !sellerreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sellerreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sellerreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(sellerreview.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(sellerreview.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(sellerreview.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(sellerreview.FieldComment, field.TypeString)
	}
	if _u.mutation.SellerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.SellerTable,
			Columns: []string{sellerreview.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SellerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.SellerTable,
			Columns: []string{sellerreview.SellerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seller.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.CustomerTable,
			Columns: []string{sellerreview.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sellerreview.CustomerTable,
			Columns: []string{sellerreview.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SellerReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sellerreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
