// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/entregamais/platform/backend/ent/asset"
	"github.com/entregamais/platform/backend/ent/predicate"
	"github.com/entregamais/platform/backend/ent/upload"
	"github.com/entregamais/platform/backend/ent/user"
)

// UploadUpdate is the builder for updating Upload entities.
type UploadUpdate struct {
	config
	hooks    []Hook
	mutation *UploadMutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdate) Where(ps ...predicate.Upload) *UploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadUpdate) SetUpdatedAt(v time.Time) *UploadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *UploadUpdate) SetFilename(v string) *UploadUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableFilename(v *string) *UploadUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UploadUpdate) SetResourceID(v string) *UploadUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableResourceID(v *string) *UploadUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UploadUpdate) ClearResourceID() *UploadUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadUpdate) SetStatus(v string) *UploadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableStatus(v *string) *UploadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UploadUpdate) SetUserID(id string) *UploadUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UploadUpdate) SetUser(v *User) *UploadUpdate {
	return _u.SetUserID(v.ID)
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (_u *UploadUpdate) SetAssetID(id string) *UploadUpdate {
	_u.mutation.SetAssetID(id)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *UploadUpdate) SetAsset(v *Asset) *UploadUpdate {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdate) Mutation() *UploadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UploadUpdate) ClearUser() *UploadUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *UploadUpdate) ClearAsset() *UploadUpdate {
	_u.mutation.ClearAsset()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := upload.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Upload.filename": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Upload.user"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Upload.asset"`)
	}
	return nil
}

func (_u *UploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(upload.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upload.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(upload.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upload.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.UserTable,
			Columns: []string{upload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.UserTable,
			Columns: []string{upload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.AssetTable,
			Columns: []string{upload.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.AssetTable,
			Columns: []string{upload.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadUpdateOne is the builder for updating a single Upload entity.
type UploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadUpdateOne) SetUpdatedAt(v time.Time) *UploadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *UploadUpdateOne) SetFilename(v string) *UploadUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableFilename(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *UploadUpdateOne) SetResourceID(v string) *UploadUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableResourceID(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *UploadUpdateOne) ClearResourceID() *UploadUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadUpdateOne) SetStatus(v string) *UploadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableStatus(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UploadUpdateOne) SetUserID(id string) *UploadUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UploadUpdateOne) SetUser(v *User) *UploadUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAssetID sets the "asset" edge to the Asset entity by ID.
func (_u *UploadUpdateOne) SetAssetID(id string) *UploadUpdateOne {
	_u.mutation.SetAssetID(id)
	return _u
}

// SetAsset sets the "asset" edge to the Asset entity.
func (_u *UploadUpdateOne) SetAsset(v *Asset) *UploadUpdateOne {
	return _u.SetAssetID(v.ID)
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdateOne) Mutation() *UploadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UploadUpdateOne) ClearUser() *UploadUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAsset clears the "asset" edge to the Asset entity.
func (_u *UploadUpdateOne) ClearAsset() *UploadUpdateOne {
	_u.mutation.ClearAsset()
	return _u
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdateOne) Where(ps ...predicate.Upload) *UploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadUpdateOne) Select(field string, fields ...string) *UploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Upload entity.
func (_u *UploadUpdateOne) Save(ctx context.Context) (*Upload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdateOne) SaveX(ctx context.Context) *Upload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := upload.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Upload.filename": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Upload.user"`)
	}
	if _u.mutation.AssetCleared() && len(_u.mutation.AssetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Upload.asset"`)
	}
	return nil
}

func (_u *UploadUpdateOne) sqlSave(ctx context.Context) (_node *Upload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upload.FieldID)
		for _, f := range fields {
			if !upload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upload.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(upload.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(upload.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(upload.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upload.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.UserTable,
			Columns: []string{upload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.UserTable,
			Columns: []string{upload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.AssetTable,
			Columns: []string{upload.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upload.AssetTable,
			Columns: []string{upload.AssetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Upload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
