apisix:
  node_listen: 9080
  enable_admin: true
  enable_control: true
  ssl:
    enable: true
    listen:
      - port: 9443

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

nginx_config:
  error_log_level: warn
