services:
  backend:
    restart: always
  frontend:
    restart: always
  fiscal:
    restart: always
  gateway:
    restart: always
    ports: ["80:9080"]
  keycloak:
    restart: always
  postgres:
    restart: always
  postgres-auth:
    restart: always
  dolibarr-db:
    restart: always
  dolibarr:
    restart: always
  redis:
    restart: always
  minio:
    restart: always
  rabbitmq:
    restart: always
  elasticsearch:
    restart: always
  logstash:
    restart: always
  kibana:
    restart: always
