services:
  backend:
    restart: always
  frontend:
    restart: always
  fiscal:
    restart: always
  gateway:
    restart: always
    ports: ["80:9080"]
  keycloak:
    restart: always
  postgres:
    restart: always
  postgres-auth:
    restart: always
  dolibarr-db:
    restart: always
  dolibarr:
    restart: always
  redis:
    restart: always
  minio:
    restart: always
  rabbitmq:
    restart: always
  loki:
    restart: always
  promtail:
    restart: always
  grafana:
    restart: always
    ports: ["5601:3000"]
